package com.codebosses.flicks.endpoints;

public interface EndpointKeys {

    String THE_MOVIE_DB_API_KEY = "0021549a1c767c99bc531d078d1cda1a";
    String GOOGLE_API_KEY = "AIzaSyCC_bwgm7pwXmBe6AobsaZIxSPCpknFJSo";
    String VIDEO_SPIDER_KEY = "SDpxVZhrUXd8zzxu";
    String VIDEO_SPIDER_SECRET_KEY = "njbu872wom79c60l3c3q6cojavt3qy";

    String UPCOMING_MOVIES = "Upcoming Movies";
    String TOP_RATED_MOVIES = "Top Rated Movies";
    String LATEST_MOVIES = "Latest Movies";
    String IN_THEATER = "In Theater";
    String TOP_RATED_TV_SHOWS = "Top Rated Tv Shows";
    String LATEST_TV_SHOWS = "Latest Tv Shows";
    String TV_SHOWS_ON_THE_AIR = "Tv Shows On Air";
    String TV_SHOWS_AIRING_TODAY = "Tv Shows Airing Today";
    String TOP_RATED_CELEBRITIES = "Top Rated Celebrities";
    String ACTION = "Action";
    String ANIMATED = "Animated";
    String DRAMA = "Drama";
    String SCIENCE_FICTION = "Science Fiction";
    String SIMILAR_MOVIES = "Similar Movies";
    String SIMILAR_MOVIES_DETAIL = "Similar Movies Detail";
    String SUGGESTED_MOVIES_DETAIL = "Suggested Movies Detail";
    String SUGGESTED_MOVIES = "Suggested Movies";
    String KNOW_FOR_MOVIES = "Known For Movies";
    String SIMILAR_TV_SHOWS = "Similar Tv Shows";
    String SUGGESTED_TV_SHOWS = "Suggested Tv Shows";
    String SEARCH_MOVIE = "Search Movie";
    String SEARCH_TV_SHOW = "Search Tv Show";
    String SEARCH_CELEBRITY = "Search Celebrity";
    String CELEBRITY_MOVIES = "Celeb Movies";
    String SIMILAR_TV_SHOWS_DETAIL = "Similar Tv Shows Detail";
    String SUGGESTED_TV_SHOWS_DETAIL = "Suggested Tv Shows Detail";
    String TRENDING = "Trending";
    String OFFLINE = "Offline";
    String SEASON = "Season";
    String TRENDING_MOVIES = "Trending Movies";
    String TRENDING_TV_SHOWS = "Trending Tv Shows";
    String TRENDING_CELEBRITIES = "Trending Celebrities";
    String DISCOVER = "Discover";
    String GENRE = "Genre";
    String MOVIES_GENRE = "Movies Genre";
    String TV_SHOWS_GENRE = "Tv Shows Genre";
    String ACTION_MOVIES = "action_movies";
    String ADVENTURE_MOVIES = "adventure_movies";
    String ANIMATED_MOVIES = "animated_movies";
    String ROMANTIC_MOVOES = "romantic_movies";
    String SCIENCE_FICTION_MOVIES = "science_fiction_movies";
    String CRIME_MOVIES = "crime_movies";
    String GENRE_MOVIES = "genre_movies";
    String HORROR_MOVIES = "horror_movies";
    String THRILLER_MOVIES = "thriller_movies";
    String COMEDY_MOVIES = "comedy_movies";
    String FAMILY_MOVIES = "family_movies";
    String ACTION_TV_SHOWS = "action_tv_shows";
    String ADVENTURE_TV_SHOWS = "adventure_tv_shows";
    String ANIMATED_TV_SHOWS = "animated_tv_shows";
    String ROMANTIC_TV_SHOWS = "romantic_tv_shows";
    String CRIME_TV_SHOWS = "crime_tv_shows";
    String THRILLER_TV_SHOWS = "thrill_tv_shows";
    String COMEDY_TV_SHOWS = "comedy_tv_shows";
    String HORROR_TV_SHOWS = "horror_tv_shows";
    String SCIENCE_FICTION_TV_SHOWS = "science_fiction_tv_shows";
    String SORT_TYPE = "sort_type";
    String MOVIES = "Movies";
    String TV_SHOWS = "Tv Shows";

    String API_KEY = "api_key";
    String LANGUAGE = "language";
    String PAGE = "page";
    String REGION = "region";
    String MOVIE_ID = "movie_id";
    String MOVIE_TITLE = "movie_title";
    String RATING = "rating";
    String CELEBRITY_ID = "celebrity_id";
    String CELEB_MOVIES = "celeb_movies";
    String CELEB_TV_SHOWS = "celeb_tv_shows";
    String CELEB_NAME = "celeb_name";
    String CELEB_IMAGE = "celeb_image";
    String TV_ID = "tv_id";
    String TV_NAME = "tv_name";
    String QUERY = "query";
    String INCLUDE_ADULT = "include_adult";
    String CAST = "cast";
    String CREW = "crew";
    String PERSON_ID = "person_id";
    String SEASON_NUMBER = "season_number";
    String EPISODE = "episode";
    String EPISODE_NUMBER = "episode_number";
    String EPISODE_DETAIL = "episode_detail";
    String MEDIA_TYPE = "media_type";
    String TIME_WINDOW = "time_window";
    String NOTIFICATION_TYPE = "notification_type";
    String YOUTUBE_KEY = "youtube_key";
    String GENRE_TYPE = "genre_type";
    String CELEBRITY_TV_SHOWS = "celebrity_tv_shows";
    String GENRE_ID = "genre_id";
    String MOVIE_URL = "movie_url";

    String CELEBRITY_IMAGES = "celebrity_images";
    String EPISODE_IMAGES = "episode_images";
    String MOVIES_IMAGES = "movies_images";
    String TV_SEASON_IMAGES = "tv_season_images";
    String TV_SHOW_IMAGES = "tv_show_images";
    String TYPE = "type";
    String IMAGE_POSITION = "image_position";
    String GENRE_TV_SHOWS = "genre_tv_shows";


    String VIDEO_PATH = "video_path";
}

